const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const tools = [
  // AI 对话
  {
    name: "ChatGPT",
    slug: "chatgpt",
    description: "OpenAI 开发的强大 AI 对话助手，支持文本、代码、图像等多种交互方式。",
    url: "https://chat.openai.com",
    icon: "💬",
    category: "chat",
    tags: ["对话", "写作", "编程"],
    pricing: "freemium",
    rating: 4.8,
    featured: true,
  },
  {
    name: "Claude",
    slug: "claude",
    description: "Anthropic 开发的 AI 助手，以安全和有帮助著称，擅长长文本理解和分析。",
    url: "https://claude.ai",
    icon: "🤖",
    category: "chat",
    tags: ["对话", "分析", "写作"],
    pricing: "freemium",
    rating: 4.9,
    featured: true,
  },
  {
    name: "Gemini",
    slug: "gemini",
    description: "Google 的多模态 AI 模型，支持文本、图像、音频等多种输入。",
    url: "https://gemini.google.com",
    icon: "✨",
    category: "chat",
    tags: ["对话", "多模态"],
    pricing: "freemium",
    rating: 4.5,
    featured: true,
  },
  {
    name: "DeepSeek",
    slug: "deepseek",
    description: "国产大模型，擅长代码和数学推理，提供高性价比的 API 服务。",
    url: "https://chat.deepseek.com",
    icon: "🔍",
    category: "chat",
    tags: ["对话", "编程", "推理"],
    pricing: "freemium",
    rating: 4.6,
  },
  {
    name: "文心一言",
    slug: "wenxin",
    description: "百度推出的大语言模型，支持中文理解和生成。",
    url: "https://yiyan.baidu.com",
    icon: "📝",
    category: "chat",
    tags: ["对话", "中文"],
    pricing: "freemium",
    rating: 4.2,
  },

  // AI 编程
  {
    name: "Cursor",
    slug: "cursor",
    description: "AI 原生代码编辑器，内置 AI 助手，支持代码生成、重构和调试。",
    url: "https://cursor.sh",
    icon: "⚡",
    category: "coding",
    tags: ["编程", "编辑器", "AI编程"],
    pricing: "freemium",
    rating: 4.9,
    featured: true,
  },
  {
    name: "GitHub Copilot",
    slug: "github-copilot",
    description: "GitHub 的 AI 编程助手，支持代码补全和生成。",
    url: "https://github.com/features/copilot",
    icon: "✈️",
    category: "coding",
    tags: ["编程", "代码补全"],
    pricing: "paid",
    rating: 4.7,
    featured: true,
  },
  {
    name: "v0.dev",
    slug: "v0",
    description: "Vercel 推出的 AI 生成 UI 组件工具，快速生成 React 代码。",
    url: "https://v0.dev",
    icon: "🎨",
    category: "coding",
    tags: ["UI", "React", "前端"],
    pricing: "freemium",
    rating: 4.6,
  },
  {
    name: "Bolt.new",
    slug: "bolt",
    description: "AI 驱动的全栈应用开发平台，从想法到部署一步到位。",
    url: "https://bolt.new",
    icon: "⚡",
    category: "coding",
    tags: ["全栈", "应用开发"],
    pricing: "freemium",
    rating: 4.5,
  },
  {
    name: "Replit AI",
    slug: "replit-ai",
    description: "在线编程平台，内置 AI 助手帮助编写和调试代码。",
    url: "https://replit.com",
    icon: "💻",
    category: "coding",
    tags: ["在线编程", "协作"],
    pricing: "freemium",
    rating: 4.4,
  },

  // AI 图像
  {
    name: "Midjourney",
    slug: "midjourney",
    description: "顶级 AI 图像生成工具，艺术风格独特，效果惊艳。",
    url: "https://midjourney.com",
    icon: "🎨",
    category: "image",
    tags: ["图像生成", "艺术"],
    pricing: "paid",
    rating: 4.9,
    featured: true,
  },
  {
    name: "DALL·E 3",
    slug: "dalle",
    description: "OpenAI 的图像生成模型，支持精确的文本描述生成图像。",
    url: "https://openai.com/dall-e-3",
    icon: "🖼️",
    category: "image",
    tags: ["图像生成"],
    pricing: "paid",
    rating: 4.7,
  },
  {
    name: "Stable Diffusion",
    slug: "stable-diffusion",
    description: "开源的图像生成模型，可本地部署，社区活跃。",
    url: "https://stability.ai",
    icon: "🌟",
    category: "image",
    tags: ["图像生成", "开源"],
    pricing: "free",
    rating: 4.6,
  },
  {
    name: "Leonardo.AI",
    slug: "leonardo",
    description: "AI 图像生成平台，专注于游戏资产和创意设计。",
    url: "https://leonardo.ai",
    icon: "🎭",
    category: "image",
    tags: ["图像生成", "游戏"],
    pricing: "freemium",
    rating: 4.5,
  },
  {
    name: "Remove.bg",
    slug: "remove-bg",
    description: "AI 自动抠图工具，一键去除图片背景。",
    url: "https://remove.bg",
    icon: "✂️",
    category: "image",
    tags: ["抠图", "背景移除"],
    pricing: "freemium",
    rating: 4.6,
  },

  // AI 视频
  {
    name: "Runway",
    slug: "runway",
    description: "AI 视频生成和编辑平台，支持文生视频、图生视频等功能。",
    url: "https://runway.ml",
    icon: "🎬",
    category: "video",
    tags: ["视频生成", "视频编辑"],
    pricing: "freemium",
    rating: 4.7,
    featured: true,
  },
  {
    name: "Pika Labs",
    slug: "pika",
    description: "AI 视频生成工具，支持创意视频制作。",
    url: "https://pika.art",
    icon: "🎥",
    category: "video",
    tags: ["视频生成"],
    pricing: "freemium",
    rating: 4.5,
  },
  {
    name: "Sora",
    slug: "sora",
    description: "OpenAI 的文生视频模型，生成高质量长视频。",
    url: "https://openai.com/sora",
    icon: "🌟",
    category: "video",
    tags: ["视频生成"],
    pricing: "paid",
    rating: 4.9,
  },

  // AI 音频
  {
    name: "ElevenLabs",
    slug: "elevenlabs",
    description: "顶级 AI 语音合成平台，支持多语言、多音色配音。",
    url: "https://elevenlabs.io",
    icon: "🎙️",
    category: "audio",
    tags: ["语音合成", "配音"],
    pricing: "freemium",
    rating: 4.8,
    featured: true,
  },
  {
    name: "Suno AI",
    slug: "suno",
    description: "AI 音乐生成工具，输入文字即可创作歌曲。",
    url: "https://suno.ai",
    icon: "🎵",
    category: "audio",
    tags: ["音乐生成"],
    pricing: "freemium",
    rating: 4.7,
    featured: true,
  },
  {
    name: "Whisper",
    slug: "whisper",
    description: "OpenAI 的语音识别模型，支持多语言转录。",
    url: "https://openai.com/research/whisper",
    icon: "👂",
    category: "audio",
    tags: ["语音识别", "转录"],
    pricing: "free",
    rating: 4.8,
  },

  // 效率工具
  {
    name: "Notion AI",
    slug: "notion-ai",
    description: "Notion 内置 AI 助手，帮助写作、总结、头脑风暴。",
    url: "https://notion.so",
    icon: "📝",
    category: "productivity",
    tags: ["笔记", "写作", "协作"],
    pricing: "freemium",
    rating: 4.6,
  },
  {
    name: "Perplexity",
    slug: "perplexity",
    description: "AI 搜索引擎，提供带来源的精准答案。",
    url: "https://perplexity.ai",
    icon: "🔍",
    category: "productivity",
    tags: ["搜索", "研究"],
    pricing: "freemium",
    rating: 4.8,
    featured: true,
  },
  {
    name: "Gamma",
    slug: "gamma",
    description: "AI 生成演示文稿，快速创建专业 PPT。",
    url: "https://gamma.app",
    icon: "📊",
    category: "productivity",
    tags: ["PPT", "演示"],
    pricing: "freemium",
    rating: 4.5,
  },
  {
    name: "Otter.ai",
    slug: "otter",
    description: "AI 会议记录工具，自动转录和总结会议内容。",
    url: "https://otter.ai",
    icon: "🦦",
    category: "productivity",
    tags: ["会议", "转录"],
    pricing: "freemium",
    rating: 4.4,
  },
];

async function main() {
  console.log('开始同步 AI 工具...');
  
  for (const tool of tools) {
    await prisma.aITool.upsert({
      where: { slug: tool.slug },
      update: {},
      create: {
        ...tool,
        tags: tool.tags,
        published: true,
      },
    });
    console.log(`已添加: ${tool.name}`);
  }
  
  const total = await prisma.aITool.count();
  console.log(`\n✅ 工具总数: ${total}`);
}

main().catch(console.error).finally(() => prisma.$disconnect());